[package]
name = "compact-id-map"
version = "0.1.0"
edition = "2021"

[dependencies]
hashbrown = { version = "0.15.2", features = ["serde"] }
increment = "0.3.0"
serde = { version = "1.0.219", features = ["derive"] }
